source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.1'
use_frameworks!

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
pod 'SCLAlertView'

target 'MenuApp' do
    pod 'Alamofire', '~> 4.0'
end

target 'MenuAppTests' do

end

target 'MenuAppUITests' do

end

